### ISSUE TITLE
Unknown setting 'message_format' for webhdfs 

### ISSUE THREAD

**Issue by langke93** [logstash-plugins/logstash-output-webhdfs#25]
- Version:logstash-2.3.4  
  - Operating System:linux  
  - Config File :  
    output{  
    webhdfs{  
    host => "sea2"  
    codec => "json"  
    standby_host => "sea3"  
    path => "/cdnlog/%{+YYYYMMdd}/%{+HH}/%{+mm}/cnc_192.log"  
    message_format =>"%{message}"  
    user => "hadoop"  
    }  
    }  
- Steps to Reproduce:  
  input data ：1473738019.430 \"116.228.11.210\" 375 \"GET\"  
  output hdfs file : 2016-09-13T03:39:58.642Z %{host} 1473738019.430 "116.228.11.210"  375 "GET"  

More output in front of a timestamp and % {host}, but I don't need them

**Comment by langke93** [comment]
And also want to reflect the parameters in the document:https://www.elastic.co/guide/en/logstash/2.3/plugins-outputs-webhdfs.html#plugins-outputs-webhdfs-message_format

**Comment by dstore-dbap** [comment]
Hello langke93 !

Thanks for your feedback and problem report. I will have a look at this problem in the next couple of days and get back to you as soon as I have some news.

Take care,
Björn

**Comment by dstore-dbap** [comment]
Hi again!

The configuration option 'message_format' was removed in commit https://github.com/logstash-plugins/logstash-output-webhdfs/commit/8f1cf04a26eeadf9c448ae7da90af5af8ffee220#diff-d807ea36853d4e0b3acf6ef50b87c259. 
Please use the format option of the line output codec instead. E.g.:
`output {
webhdfs {
   host => ...
   ....
   codec => {
        line {
                format => "custom format: %{message}"
        }
   }
 }
}`

Still, we need to check why the documentation does not reflect the current code and sorry for the confusion, caused by this!

So thank you very much for pointing this out and for your commit! Still, as the default way should be to use the line codec with the format parameter, I will not merge your commit. Not because it's bad or anything ;)

Take care and all the best,
Björn

I will leave this issue open until we found out, why the documentations is not up to date.

**Comment by langke93** [comment]
output{  
  webhdfs{
    host => "sea2"
    standby_host => "sea3"
    codec => {line { format => "custom format: %{message}"}}
 }  
}  
tips: 
The given configuration is invalid. Reason: Expected one of #, => at line 35, column 20 (byte 1427) after output {  
  webhdfs{  
    host => "sea2"  
    standby_host => "sea3"  
    codec => {line  {:level=>:fatal}  

And then I modify:  
    codec => {line =>{ format => "custom format: %{message}"}}
Then prompt :  

Pipeline aborted due to error {:exception=>#<NoMethodError: undefined method `on_event' for ["line", {"format"=>"custom format: %{message}"}]:Array>

**Comment by dstore-dbap** [comment]
My bad ;)

The example I gave was invalid, as you correctly pointed out. 
Correct example:

webhdfs{
host => "sea2"
standby_host => "sea3"
codec => line { format => "custom format: %{message}"}
}

Sorry for this mistake!

Take care,
Björn

**Comment by dstore-dbap** [comment]
Hello langke93 !

Could you please let me know if this new configuration does work for you?
If so, this issue could be closed.

Take care and have a nice weekend,
Björn

**Comment by langke93** [comment]
thanks,is ok
